name: cicd
on:  
  workflow_dispatch:

jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: clone the code 
        run: echo "Cloning the code..."
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build the code
        run: echo "Building the code..."
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test the code
        run: echo "Testing the code"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy the code
        run: echo "Deploying the code"

    
